### ISSUE TITLE
windows wheels not uploading

### ISSUE THREAD

**Issue by jswhit** [MacPython/cftime-wheels#1]
on appveyor, `python -m wheelhouse_uploader upload --local-folder=dist --no-update-index wheels` produces:

`WARNING: secret API key missing: skipping package upload`

I wonder if the key in appveyor.yml is correct

      WHEELHOUSE_UPLOADER_USERNAME: travis-worker
      WHEELHOUSE_UPLOADER_SECRET:
        secure:
            9s0gdDGnNnTt7hvyNpn0/ZzOMGPdwPp2SewFTfGzYk7uI+rdAN9rFq2D1gAP4NQh

@matthew-brett, it looks like this was copied from numpy-wheels.  linux and macosx uploads work, so I assume the encrypted key in .travis.yml is correct for this project - I guess we need a version of this key encrypted for appveyor (using the appveyor encryption key).

**Comment by jswhit** [comment]
@matthew-brett, is it possible to have an api key for appveyor windows builds?

**Comment by matthew-brett** [comment]
Yes, OK - can you email me?  I'll send it on.

**Comment by matthew-brett** [comment]
Actually - I found your email - I've emailed you.

**Comment by jswhit** [comment]
Working now, thanks!
