### ISSUE TITLE
python 3.8 builds failing

### ISSUE THREAD

**Issue by jswhit** [MacPython/cftime-wheels#2]
https://travis-ci.org/MacPython/cftime-wheels/jobs/600076288

/io/multibuild/common_utils.sh: line 231: pip: command not found

**Comment by jswhit** [comment]
updating multibuilds did not fix it.

**Comment by jswhit** [comment]
@matthew-brett: any idea what might be causing this?

**Comment by matthew-brett** [comment]
It looks like you have an old version of multibuild.  You need the latest
commit on the devel branch, to pull in the changes for Python 3.8.

**Comment by jswhit** [comment]
Yes, that was it  - thanks!
