### ISSUE TITLE
install_run $PLAT failing with pip error

### ISSUE THREAD

**Issue by jswhit2** [MacPython/cftime-wheels#3]
ERROR: You must give at least one requirement to install (maybe you meant "pip install https://5cf40426d9f06eb7461d-6fe47d9331aba7cd62fc36c7196769e4.ssl.cf2.rackcdn.com"?)

see https://travis-ci.org/MacPython/cftime-wheels

@matthew-brett - any suggestions?

**Comment by matthew-brett** [comment]
I think that's the pip 20 error : https://github.com/matthew-brett/multibuild/issues/298 - did you already try updating to latest multibuild?

**Comment by jswhit2** [comment]
Thought I did, but apparently I didn't.  Updating to the latest devel does indeed fix it - thanks!
